import type { Metadata } from 'next'
import { Inter, VT323, Roboto_Mono, Playfair_Display } from 'next/font/google'
import { Toaster } from '@/components/ui/sonner'
import './globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const vt323 = VT323({
  weight: '400',
  variable: '--font-vt323',
  subsets: ['latin'],
})

const robotoMono = Roboto_Mono({
  weight: ['100', '300', '400', '500', '700'],
  variable: '--font-roboto-mono',
  subsets: ['latin'],
})

const playfairDisplay = Playfair_Display({
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-playfair-display',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.variable} ${vt323.variable} ${robotoMono.variable} ${playfairDisplay.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  )
}
