export const SKILLS = [
  'Front-End Development',
  'React',
  'React Native',
  'TypeScript',
  'JavaScript',
  'Vue.js',
  'Next.js',
  'Nuxt.js',
  'NuxtUI',
  'HTML5',
  'CSS3',
  'Tailwind CSS',
  'Nativewind',
  'Mobile Development',
  'Gluestack',
  'Flashlist',
  'Cross-Platform Development',
  'React Native Reanimated',
  'Motion',
  'Expo',
  'Web3',
  'Blockchain',
  'Ethers.js',
  'Wagmi',
  'Reown',
  'Figma',
  'UI/UX Design',
  'Prototyping',
  'Git',
  'GitHub',
  'CI/CD',
  'GitHub Actions',
  'Node.js',
  'Fastify',
  'JWT',
  'API Integration',
  'RESTful APIs',
  'MySQL',
  'PostgreSQL',
  'SQLite',
  'Knex.js',
  'Prisma',
  'Microsoft SQL Server',
  'AWS',
  'Cloud Computing',
  'S3',
  'RDS',
  'SQS',
  'SNS',
  'Sentry',
  'Performance Monitoring',
  'Redux',
  'Zustand',
  'Pinia',
  'React Hook Form',
  'Zod',
  'Firebase',
  'Supabase',
  'Jira',
  'Agile Metodologies',
  'Scrum',
  'Advanced Excel',
  'Linux',
  'Windows Server',
  'IT Infrastructure',
  'Security Information',
  'LGPD',
  'Firewall',
  'Fortinet',
  'Office 365',
  'Exchange Server',
  'Google Workspace',
]
